added /api/articles endpoint and modified endpoints.json
dylank03/nc-news-project pull request #4
Opened 2023-11-21 14:06 UTC by dylank03

2023-11-21 15:31 UTC, Harrison365 commented on __tests__/app.test.js
> +        })
Nice 👍

2023-11-21 15:37 UTC, Harrison365 commented on models/model.js
> +    })
This will need to join another table to get a comment count. You will also need to specify the columns you want to exclude the body properties.

2023-11-21 15:38 UTC, Harrison365 commented on __tests__/app.test.js
> +            expect(body.articles.length).toBe(testData.articleData.length)
Good length check :)

2023-11-21 15:38 UTC, Harrison365 commented on __tests__/app.test.js
> +                expect(article).toEqual(expect.objectContaining({ article_id: expect.any(Number), title: expect.any(String), topic: expect.any(String), author: expect.any(String), body: expect.any(St
Nice use of a forEach

2023-11-21 15:39 UTC, Harrison365 commented on __tests__/app.test.js
> +    })
We would also like a test to check that they are in created-at order (descending). you can use the jest-sorted package for this 👍

2023-11-22 09:26 UTC, 2202Hannah requested changes
Hi Dylan, good job implementing Harrison's feedback. This ticket is really close to being complete now. 

- Please remove the stray console.log before merging to main
- You haven't explicitly tested that your response body doesn't contain the article's body property. Please add this before merging to main. 
- Optional refactor - You could make sure that the comment count in an integer in your SQL query by casting it as int (e.g. `:: INT`) rather than a string. 

You can merge to main once you have made these changes, being mindful of any merge conflicts.

2023-11-22 09:26 UTC, 2202Hannah commented on __tests__/app.test.js
> +            console.log(body)
make sure you remove any console.logs before merging to main

2023-11-22 10:10 UTC, merged